-- MySQL Script generated by MySQL Workbench
-- Mon Dec 14 12:30:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_dados` DEFAULT CHARACTER SET utf8 ;
USE `db_dados` ;

-- -----------------------------------------------------
-- Table `db_dados`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dados`.`Client` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(60) NOT NULL,
  `Acesstoken` VARCHAR(100) NULL,
  `Document` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(125) NOT NULL,
  `Phone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;

INSERT INTO Client (Email, Document, Nome, Phone)
VALUES ('gabriel.pestrini@sou.unaerp.edu.br','000.000.000.-00','eduardo','9999-9999');
-- -----------------------------------------------------
-- Table `db_dados`.`Api`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dados`.`Api` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;

INSERT INTO Api (Nome)
VALUES ('MailPHP');

-- -----------------------------------------------------
-- Table `db_dados`.`ClientApi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dados`.`ClientApi` (
  `ClientId` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `Api_Id` INT NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ClientId`),
  INDEX `fk_ClientApi_Client1_idx` (`idClient` ASC),
  INDEX `fk_ClientApi_Api1_idx` (`Api_Id` ASC),
  CONSTRAINT `fk_ClientApi_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `db_dados`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClientApi_Api1`
    FOREIGN KEY (`Api_Id`)
    REFERENCES `db_dados`.`Api` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO ClientApi(idClient, Api_Id, Username, Password)
VALUES ('1','1','user123',md5('12345'));


-- -----------------------------------------------------
-- Table `db_dados`.`ClientPlan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dados`.`ClientPlan` (
  `idPlan` INT NOT NULL AUTO_INCREMENT,
  `idClient` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `MonthlyValue` FLOAT NOT NULL,
  `RequestValue` FLOAT NOT NULL,
  `ContratedQuantity` FLOAT NOT NULL,
  `ExtraQuantity` FLOAT NOT NULL,
  PRIMARY KEY (`idPlan`),
  INDEX `fk_ClientPlan_Client1_idx` (`idClient` ASC),
  CONSTRAINT `fk_ClientPlan_Client1`
    FOREIGN KEY (`idClient`)
    REFERENCES `db_dados`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO ClientPlan (idClient, Nome, MonthlyValue, RequestValue, ContratedQuantity, ExtraQuantity)
VALUES ('1','chamada ilimitada', '50', '0.05', '1000', '0');

INSERT INTO ClientPlan (idClient, Nome, MonthlyValue, RequestValue, ContratedQuantity, ExtraQuantity)
VALUES ('1','SMS ilimitada', '50', '0.01', '5000', '0');


-- -----------------------------------------------------
-- Table `db_dados`.`ClientConfig`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dados`.`ClientConfig` (
  `ID` INT NOT NULL,
  `ClientId` INT NOT NULL,
  `SMTPUsername` VARCHAR(45) NOT NULL,
  `SMTPHost` VARCHAR(45) NOT NULL,
  ` SMTPPassword` VARCHAR(45) NOT NULL,
  `SMTPPort` INT NOT NULL,
  `TrackingEmailTemplate` VARCHAR(500) NULL,
  `TrackingEmailEventTemplate` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_ClientConfig_Client1_idx` (`ClientId` ASC),
  CONSTRAINT `fk_ClientConfig_Client1`
    FOREIGN KEY (`ClientId`)
    REFERENCES `db_dados`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_dados`.`ClientApiRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_dados`.`ClientApiRequest` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `PlanId` INT NOT NULL,
  `ClientId` INT NOT NULL,
  `dt_request` DATETIME NULL,
  `Url` VARCHAR(100) NULL,
  `Body` VARCHAR(300) NULL,
  `ResponseStatus` INT NULL,
  `ResponseBody` VARCHAR(300) NULL,
  `PostAction` VARCHAR(300) NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ClientApiRequest_ClientPlan1_idx` (`PlanId` ASC),
  INDEX `fk_ClientApiRequest_Client1_idx` (`ClientId` ASC),
  CONSTRAINT `fk_ClientApiRequest_ClientPlan1`
    FOREIGN KEY (`PlanId`)
    REFERENCES `db_dados`.`ClientPlan` (`idPlan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClientApiRequest_Client1`
    FOREIGN KEY (`ClientId`)
    REFERENCES `db_dados`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




